variables:
  targetPath:  '$(Build.SourcesDirectory)/H5/H5.Build.Target/H5.Build.Target.csproj'
  buildConfiguration: 'Release'

pool:
  vmImage: 'windows-latest'

trigger: 
  branches:
    include:
    - master
  paths:
    include:
    - H5/H5.Build.Target/*
    - .devops/build-h5-target.yml

pr: none

steps:
- checkout: self
  
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: sdk
    version: 5.0.100
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  displayName: 'restore nuget'
  inputs:
    command: 'restore'
    projects: '$(targetPath)'

- task: DotNetCoreCLI@2
  displayName: 'pack nuget'
  inputs:
    command: 'pack'
    packagesToPack: '$(targetPath)'
    configuration: '$(buildConfiguration)'
    versioningScheme: 'off'
    buildProperties: 'Version="0.0.$(build.buildId)"'

- task: NuGetCommand@2
  displayName: 'push nuget'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/h5.Target.0.0.$(build.buildId).nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'nuget-curiosity'